//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.WebAPI.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterDetail
    {
        public int ID { get; set; }
        public int TenantID { get; set; }
        public int CourseID { get; set; }
        public string ChapterTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        
        public virtual CourseDetail CourseDetail { get; set; }

        public virtual ICollection<ChapterContent> ChapterContents { get; set; }

    }
}
