//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.WebAPI.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int ID { get; set; }
        public int TenantID { get; set; }
        public string CourseTitle { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public int CourseStatusID { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> SentForReviewDate { get; set; }
        public Nullable<int> Reviewer { get; set; }
        public Nullable<System.DateTime> ReviewedON { get; set; }
        public Nullable<int> CourseImageID { get; set; }
        public string Tags { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Enrollments { get; set; }

        public virtual ICollection<ChapterDetail> ChapterDetails { get; set; }

    }
}
