//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.WebAPI.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Password { get; set; }
        public Nullable<int> TenantID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public byte GenderID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> VaildUpTo { get; set; }
        public string DisplayPicURL { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> ThirdPartyProviderID { get; set; }
        public Nullable<System.DateTime> LastLoggedIN { get; set; }
        public string DefaultLandingPage { get; set; }
        public string MobileNumber { get; set; }
        public string Interest { get; set; }
    }
}
