//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELearning.WebAPI.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int ID { get; set; }
        public int TenantID { get; set; }
        public string Notification { get; set; }
        public int Status { get; set; }
        public bool Unread { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public int UserID { get; set; }
    }
}
